#include "FilenameLists.h"

FileNameList g_lstNonEncFileNames;
FileNameList g_lstNonEncFolderNames;

void InitializeNonEncryptedFiles()
{
	//Core system files
	g_lstNonEncFileNames.push_back("SV.T");
	g_lstNonEncFileNames.push_back("sv.t");
	//g_lstNonEncFileNames.push_back("media\\sv.t");

	g_lstNonEncFileNames.push_back("Media\\sv.t");
	g_lstNonEncFileNames.push_back("Media\\SV.T");

	g_lstNonEncFileNames.push_back("media\\sv.t");
	g_lstNonEncFileNames.push_back("media\\SV.T");
	g_lstNonEncFileNames.push_back("Media\\server_dep\\silkroad\\textdata\\charactervisualchange.txt");
	g_lstNonEncFileNames.push_back("Media\\interface\\ifcommon\\cop_notice_corner.ddj");
	g_lstNonEncFileNames.push_back("Media\\interface\\ifcommon\\cop_notice_edge.ddj");
	g_lstNonEncFileNames.push_back("Media\\interface\\ifcommon\\cop_notice_edge2.ddj");
	g_lstNonEncFileNames.push_back("Media\\interface\\ifcommon\\coq_notice_corner.ddj");
	g_lstNonEncFileNames.push_back("Media\\interface\\ifcommon\\coq_notice_edge.ddj");
	g_lstNonEncFileNames.push_back("Media\\interface\\ifcommon\\coq_notice_edge2.ddj");

	g_lstNonEncFolderNames.push_back("Media\\interface");
	g_lstNonEncFolderNames.push_back("Media\\maxiguard");

	//[SBot 1.0.38, MBot, Media.pk2]

	/*
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\textdataname.txt");

	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\characterdata.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\characterdata_5000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\characterdata_10000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\characterdata_15000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\characterdata_20000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\characterdata_25000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\characterdata_30000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\characterdata_35000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\characterdata_40000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\characterdata_45000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\characterdata_50000.txt");

	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldataenc.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_5000enc.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_10000enc.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_15000enc.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_20000enc.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_25000enc.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_30000enc.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_35000enc.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_40000enc.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_45000enc.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_50000enc.txt");

	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\itemdata.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\itemdata_5000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\itemdata_10000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\itemdata_15000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\itemdata_20000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\itemdata_25000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\itemdata_30000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\itemdata_35000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\itemdata_40000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\itemdata_45000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\itemdata_50000.txt");

	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\magicoption.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\textuisystem.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\refshopgroup.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\refmappingshopgroup.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\refmappingshopwithtab.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\refshoptab.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\refscrapofpackageitem.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\npcpos.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\leveldata.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\teleportbuilding.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\teleportlink.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\teleportdata.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\refskillbyitemoptleveldata.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\refeventrewarditems.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\refshopgoods.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\refabilitybyitemoptleveldata.txt");

	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_5000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_10000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_15000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_20000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_25000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_30000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_35000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_40000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_45000.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_50000.txt");

	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\refextraabilitybyequipitemoptlevel.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\refsetitemgroup.txt");

	*/


	//[phBot, not yet complete list (coz data & other stuff)]
	/*
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\gamedataconfig.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\tradeconflict_joblevel.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\textdata_object.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\textdata_equip&skill.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\textquest.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\textquest_otherstring.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\textquest_speech&name.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\textquest_queststring.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\questcontentsdata.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\questdata.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\refquestreward.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\refquestrefwarditems.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\worldmapguidedata.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\quest.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\textevent.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\refoptionalteleport.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\refeventrewarditems.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\shopdata.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\stoptabdata.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\shopitemdata.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\textzonename.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\regioninfo.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\refregion.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\gameworlddatastabil.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skillmasterydata.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skillgroup.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skilldata_r.txt");
	lstNonEncFileNames.push_back("server_dep\\silkroad\\textdata\\skillgroup.txt");
	*/


	// bypass launcher
	/*
	lstNonEncFileNames.push_back("launcher\\bg_1.dat");
	lstNonEncFileNames.push_back("launcher_europe\\bg_1.dat");
	lstNonEncFileNames.push_back("launcher_europe\\bg_2.dat");
	lstNonEncFileNames.push_back("launcher\\bg_2.dat");
	lstNonEncFileNames.push_back("launcher\\bg_3.dat");
	lstNonEncFileNames.push_back("launcher_europe\\bg_3.dat");
	lstNonEncFileNames.push_back("launcher_europe\\bg_4.dat");
	lstNonEncFileNames.push_back("launcher\\bg_4.dat");
	lstNonEncFileNames.push_back("launcher\\bg_5.dat");
	lstNonEncFileNames.push_back("launcher_europe\\bg_5.dat");
	lstNonEncFileNames.push_back("launcher_europe\\bg_6.dat");
	lstNonEncFileNames.push_back("launcher\\bg_6.dat");
	lstNonEncFileNames.push_back("launcher\\bg_7.dat");
	lstNonEncFileNames.push_back("launcher_europe\\bg_7.dat");
	lstNonEncFileNames.push_back("launcher\\bg_8.dat");
	lstNonEncFileNames.push_back("launcher\\bg_division_1.dat");
	lstNonEncFileNames.push_back("launcher_europe\\bg_division_1.dat");
	lstNonEncFileNames.push_back("launcher_europe\\bg_division_2.dat");
	lstNonEncFileNames.push_back("launcher\\bg_division_2.dat");
	lstNonEncFileNames.push_back("launcher\\bg_division_3.dat");
	lstNonEncFileNames.push_back("launcher_europe\\bg_division_3.dat");
	lstNonEncFileNames.push_back("launcher_europe\\bg_division_4.dat");
	lstNonEncFileNames.push_back("launcher\\bg_division_4.dat");
	lstNonEncFileNames.push_back("launcher\\bg_division_5.dat");
	lstNonEncFileNames.push_back("launcher_europe\\bg_division_5.dat");
	lstNonEncFileNames.push_back("launcher_europe\\bg4.dat");
	lstNonEncFileNames.push_back("launcher_europe\\bitmap_g.dat");
	lstNonEncFileNames.push_back("launcher\\bitmap_g.dat");
	lstNonEncFileNames.push_back("launcher\\cancel.dat");
	lstNonEncFileNames.push_back("launcher\\com_mid_button_cancel.dat");
	lstNonEncFileNames.push_back("launcher\\com_mid_button_ok.dat");
	lstNonEncFileNames.push_back("launcher\\config_box.dat");
	lstNonEncFileNames.push_back("launcher_europe\\config_box.dat");
	lstNonEncFileNames.push_back("launcher_europe\\config_box_02.dat");
	lstNonEncFileNames.push_back("launcher\\config_box_02.dat");
	lstNonEncFileNames.push_back("launcher\\config_bright.dat");
	lstNonEncFileNames.push_back("launcher\\config_graphic.dat");
	lstNonEncFileNames.push_back("launcher\\config_resolution.dat");
	lstNonEncFileNames.push_back("launcher\\designed by yk graphic.txt");
	lstNonEncFileNames.push_back("launcher\\division_1.dat");
	lstNonEncFileNames.push_back("launcher_europe\\division_1.dat");
	lstNonEncFileNames.push_back("launcher_europe\\division_2.dat");
	lstNonEncFileNames.push_back("launcher\\division_2.dat");
	lstNonEncFileNames.push_back("launcher\\division_3.dat");
	lstNonEncFileNames.push_back("launcher_europe\\division_3.dat");
	lstNonEncFileNames.push_back("launcher_europe\\division_4.dat");
	lstNonEncFileNames.push_back("launcher_europe\\division_5.dat");
	lstNonEncFileNames.push_back("launcher\\division_select.dat");
	lstNonEncFileNames.push_back("launcher\\exit.dat");
	lstNonEncFileNames.push_back("launcher_europe\\exit.dat");
	lstNonEncFileNames.push_back("launcher\\facebook.dat");
	lstNonEncFileNames.push_back("launcher\\gauge.dat");
	lstNonEncFileNames.push_back("launcher_europe\\gauge.dat");
	lstNonEncFileNames.push_back("launcher\\gauge_back.dat");
	lstNonEncFileNames.push_back("launcher\\guide.dat");
	lstNonEncFileNames.push_back("launcher_europe\\guide.dat");
	lstNonEncFileNames.push_back("launcher\\homepage.dat");
	lstNonEncFileNames.push_back("launcher\\homepage_1.dat");
	lstNonEncFileNames.push_back("launcher_europe\\homepage_1.dat");
	lstNonEncFileNames.push_back("launcher_europe\\homepage_2.dat");
	lstNonEncFileNames.push_back("launcher\\homepage_2.dat");
	lstNonEncFileNames.push_back("launcher\\homepage_3.dat");
	lstNonEncFileNames.push_back("launcher_europe\\homepage_3.dat");
	lstNonEncFileNames.push_back("launcher_europe\\homepage_4.dat");
	lstNonEncFileNames.push_back("launcher\\homepage_4.dat");
	lstNonEncFileNames.push_back("launcher\\homepage_5.dat");
	lstNonEncFileNames.push_back("launcher_europe\\homepage_5.dat");
	lstNonEncFileNames.push_back("launcher_europe\\homepage_6.dat");
	lstNonEncFileNames.push_back("launcher\\homepage_6.dat");
	lstNonEncFileNames.push_back("launcher\\homepage_7.dat");
	lstNonEncFileNames.push_back("launcher_europe\\homepage_7.dat");
	lstNonEncFileNames.push_back("launcher_europe\\homepage1.dat");
	lstNonEncFileNames.push_back("launcher\\launcherreview.dat");
	lstNonEncFileNames.push_back("launcher\\left.dat");
	lstNonEncFileNames.push_back("launcher_europe\\movie.dat");
	lstNonEncFileNames.push_back("launcher\\movie.dat");
	lstNonEncFileNames.push_back("launcher\\new_scroll_down.dat");
	lstNonEncFileNames.push_back("launcher_europe\\new_scroll_down.dat");
	lstNonEncFileNames.push_back("launcher\\new_scroll_up.dat");
	lstNonEncFileNames.push_back("launcher\\notice.dat");
	lstNonEncFileNames.push_back("launcher\\ok.dat");
	lstNonEncFileNames.push_back("launcher_europe\\ok.dat");
	lstNonEncFileNames.push_back("launcher\\ok_02.dat");
	lstNonEncFileNames.push_back("launcher\\option.dat");
	lstNonEncFileNames.push_back("launcher_europe\\option.dat");
	lstNonEncFileNames.push_back("launcher\\options_.dat");
	lstNonEncFileNames.push_back("launcher\\patch.dat");
	lstNonEncFileNames.push_back("launcher_europe\\patch.dat");
	lstNonEncFileNames.push_back("launcher\\patch1.dat");
	lstNonEncFileNames.push_back("launcher\\reflinkurl.txt");
	lstNonEncFileNames.push_back("launcher_europe\\reflinkurl.txt");
	lstNonEncFileNames.push_back("launcher_europe\\refresource.txt");
	lstNonEncFileNames.push_back("launcher\\refresource.txt");
	lstNonEncFileNames.push_back("launcher\\refresources.txt");
	lstNonEncFileNames.push_back("launcher_europe\\refresources.txt");
	lstNonEncFileNames.push_back("launcher\\refresources.txt.txt");
	lstNonEncFileNames.push_back("launcher\\register.dat");
	lstNonEncFileNames.push_back("launcher\\right.dat");
	lstNonEncFileNames.push_back("launcher\\scroll.dat");
	lstNonEncFileNames.push_back("launcher\\scroll_back.dat");
	lstNonEncFileNames.push_back("launcher_europe\\scroll_back.dat");
	lstNonEncFileNames.push_back("launcher_europe\\scroll_back_02.dat");
	lstNonEncFileNames.push_back("launcher\\scroll_back_02.dat");
	lstNonEncFileNames.push_back("launcher\\scroll_back_03.dat");
	lstNonEncFileNames.push_back("launcher\\scroll_back02.dat");
	lstNonEncFileNames.push_back("launcher\\scroll_down.dat");
	lstNonEncFileNames.push_back("launcher_europe\\scroll_down.dat");
	lstNonEncFileNames.push_back("launcher_europe\\scroll_move.dat");
	lstNonEncFileNames.push_back("launcher\\scroll_move.dat");
	lstNonEncFileNames.push_back("launcher\\scroll_move1.dat");
	lstNonEncFileNames.push_back("launcher_europe\\scroll_move1.dat");
	lstNonEncFileNames.push_back("launcher_europe\\scroll_up.dat");
	lstNonEncFileNames.push_back("launcher\\scroll_up.dat");
	lstNonEncFileNames.push_back("launcher\\sf_language_big_img04.dat");
	lstNonEncFileNames.push_back("launcher\\sf_language_big_img06.dat");
	lstNonEncFileNames.push_back("launcher\\sf_language_big_img07.dat");
	lstNonEncFileNames.push_back("launcher\\sf_language_big_img10.dat");
	lstNonEncFileNames.push_back("launcher\\sf_language_big_img11.dat");
	lstNonEncFileNames.push_back("launcher\\sf_language_big_no_img.dat");
	lstNonEncFileNames.push_back("launcher\\sf_language_button.dat");
	lstNonEncFileNames.push_back("launcher\\sf_language_select_frame_bottom.dat");
	lstNonEncFileNames.push_back("launcher\\sf_language_select_frame_mid.dat");
	lstNonEncFileNames.push_back("launcher\\sf_language_select_frame_top.dat");
	lstNonEncFileNames.push_back("launcher\\sf_language_small_img04.dat");
	lstNonEncFileNames.push_back("launcher\\sf_language_small_img06.dat");
	lstNonEncFileNames.push_back("launcher\\sf_language_small_img07.dat");
	lstNonEncFileNames.push_back("launcher\\sf_language_small_img10.dat");
	lstNonEncFileNames.push_back("launcher\\sf_language_small_img11.dat");
	lstNonEncFileNames.push_back("launcher\\sf_radiobutton.dat");
	lstNonEncFileNames.push_back("launcher_europe\\soundbox.dat");
	lstNonEncFileNames.push_back("launcher\\soundbox.dat");
	lstNonEncFileNames.push_back("launcher\\start.dat");
	lstNonEncFileNames.push_back("launcher_europe\\start.dat");
	lstNonEncFileNames.push_back("launcher\\startpage.dat");
	lstNonEncFileNames.push_back("launcher\\twiter.dat");
	lstNonEncFileNames.push_back("launcher\\update_focus.dat");
	lstNonEncFileNames.push_back("launcher_europe\\update_focus.dat");
	lstNonEncFileNames.push_back("launcher_europe\\update_focus1.dat");
	lstNonEncFileNames.push_back("launcher\\update_focus1.dat");
	lstNonEncFileNames.push_back("launcher\\update_select.dat");
	lstNonEncFileNames.push_back("launcher_europe\\update_select.dat");
	lstNonEncFileNames.push_back("launcher\\website.dat");
	lstNonEncFileNames.push_back("launcher\\window_close.dat");
	lstNonEncFileNames.push_back("launcher\\window_option.dat");
	lstNonEncFileNames.push_back("launcher_europe\\window_option.dat");
	lstNonEncFileNames.push_back("launcher_europe\\window_update.dat");
	lstNonEncFileNames.push_back("launcher\\window_update.dat");
	lstNonEncFileNames.push_back("launcher\\windowclose.dat");
	lstNonEncFileNames.push_back("launcher\\windows_update.dat");
	lstNonEncFileNames.push_back("launcher\\youtube.dat");
	*/

}